@ECHO OFF
COLOR 0A

SET BASE_PATH_BAT=C:\BAT\bat
SET BASE_PATH_CTL=C:\BAT\loader\ctl
SET BASE_PATH_PKG=C:\DB\Package\PKG
SET BASE_PATH_TOOLS=C:\MyTools\SetpCount\Src

SET CMD_COUNT=C:\MyTools\SetpCount\cloc.exe

:ONCE_AGAIN
ECHO 「バッチ処理ID」を入力してください（例えば：BT001_01）：
@SET /P BAT_ID=
@ECHO ON

IF NOT EXIST %BASE_PATH_TOOLS%\%BAT_ID% (
    MKDIR %BASE_PATH_TOOLS%\%BAT_ID%
)

DEL /Q /F %BASE_PATH_TOOLS%\%BAT_ID%\*

COPY %BASE_PATH_BAT%\%BAT_ID%* %BASE_PATH_TOOLS%\%BAT_ID%

COPY %BASE_PATH_CTL%\%BAT_ID%* %BASE_PATH_TOOLS%\%BAT_ID%

RENAME %BASE_PATH_TOOLS%\%BAT_ID%\%BAT_ID%.CTL %BAT_ID%.CTL.SQL

COPY %BASE_PATH_PKG%\PKG_%BAT_ID%* %BASE_PATH_TOOLS%\%BAT_ID%

DIR %BASE_PATH_TOOLS%\%BAT_ID%

"%CMD_COUNT%" %BASE_PATH_TOOLS%\%BAT_ID%

GOTO ONCE_AGAIN

PAUSE
